### ISSUE TITLE
paramaterize ancestors by predicate

### ISSUE THREAD

**Issue by cmungall** [pkalita-lbl/oak-api#2]
ancestors over all predicates is the default (maybe we should change this in OAK), this can explode. may also want to consider pageination

**Comment by pkalita-lbl** [comment]
Fixed by #4

**Comment by pkalita-lbl** [comment]
The `/class/{curie}/ancestors` and `/class/{curie}/descendants` endpoints now accept a `predicate` query parameter. It can be specified multiple times in order to include multiple predicates. It accepts [these shortcut values](https://github.com/pkalita-lbl/oak-api/blob/8630719a97af1c3a63b4ac52ef9bcfd07c36b4ce/src/oak_api/depends.py#L12-L18) or any CURIE.

**Comment by pkalita-lbl** [comment]
The `/class/{curie}/ancestors`, `/class/{curie}/descendants`, and `/search` points are now paginated. They accept `limit` (default 20) and `page` (default 1) query parameters and the response contains links to the previous and next pages of results.
